// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutomationEnabled():Promise<boolean>;

export function AutomationResult(arg1:string,arg2:string):Promise<boolean>;

export function ConfirmExit(arg1:boolean):Promise<boolean>;

export function Connect(arg1:string):Promise<main.plainResult>;

export function Disconnect(arg1:string):Promise<main.plainResult>;

export function DiscoverServices(arg1:string):Promise<main.servicesResult>;

export function GetAppVersion():Promise<string>;

export function HostPlatform():Promise<main.hostInfo>;

export function Init():Promise<main.initResult>;

export function NotifyCharacteristic(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.plainResult>;

export function ReadCharacteristic(arg1:string,arg2:string,arg3:string):Promise<main.valueResult>;

export function StartAdvertising(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:boolean):Promise<main.plainResult>;

export function StartScan():Promise<main.plainResult>;

export function StopAdvertising():Promise<main.plainResult>;

export function StopScan():Promise<main.plainResult>;

export function WriteCharacteristic(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.plainResult>;

export function WriteRaw(arg1:string,arg2:string,arg3:string,arg4:Array<number>,arg5:boolean):Promise<main.plainResult>;
