// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutomationEnabled() {
  return window['go']['main']['App']['AutomationEnabled']();
}

export function AutomationResult(arg1, arg2) {
  return window['go']['main']['App']['AutomationResult'](arg1, arg2);
}

export function ConfirmExit(arg1) {
  return window['go']['main']['App']['ConfirmExit'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DiscoverServices(arg1) {
  return window['go']['main']['App']['DiscoverServices'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function HostPlatform() {
  return window['go']['main']['App']['HostPlatform']();
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function NotifyCharacteristic(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['NotifyCharacteristic'](arg1, arg2, arg3, arg4);
}

export function ReadCharacteristic(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadCharacteristic'](arg1, arg2, arg3);
}

export function StartAdvertising(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartAdvertising'](arg1, arg2, arg3, arg4, arg5);
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}

export function StopAdvertising() {
  return window['go']['main']['App']['StopAdvertising']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function WriteCharacteristic(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['WriteCharacteristic'](arg1, arg2, arg3, arg4, arg5);
}

export function WriteRaw(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['WriteRaw'](arg1, arg2, arg3, arg4, arg5);
}
