// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppVersion():Promise<string>;

export function ScanBLE():Promise<Array<main.ScanHit>>;
