// Auto-generated by generate_assets.py
// Source: core/assets-generator/meta/colors.json
import 'package:flutter/material.dart';

class AppColors {
  // Light mode
  static const Color primaryLight = Color(0xFF1B6DFF);
  static const Color primaryDarkLight = Color(0xFF0E4FC4);
  static const Color primaryLightLight = Color(0xFFE8F1FF);
  static const Color backgroundLight = Color(0xFFF8FBFF);
  static const Color surfaceLight = Color(0xFFFFFFFF);
  static const Color borderLight = Color(0xFFE3EAF3);
  static const Color textPrimaryLight = Color(0xFF18222E);
  static const Color textSecondaryLight = Color(0xFF60758D);
  static const Color textTertiaryLight = Color(0xFF9AA8B6);
  static const Color successLight = Color(0xFF17C7A8);
  static const Color warningLight = Color(0xFFFF9F43);
  static const Color errorLight = Color(0xFFF2555F);

  // Dark mode
  static const Color primaryDark = Color(0xFF1B6DFF);
  static const Color primaryDarkDark = Color(0xFF0E4FC4);
  static const Color primaryLightDark = Color(0xFFE8F1FF);
  static const Color backgroundDark = Color(0xFFF8FBFF);
  static const Color surfaceDark = Color(0xFFFFFFFF);
  static const Color borderDark = Color(0xFFE3EAF3);
  static const Color textPrimaryDark = Color(0xFF18222E);
  static const Color textSecondaryDark = Color(0xFF60758D);
  static const Color textTertiaryDark = Color(0xFF9AA8B6);
  static const Color successDark = Color(0xFF17C7A8);
  static const Color warningDark = Color(0xFFFF9F43);
  static const Color errorDark = Color(0xFFF2555F);
}
