// Auto-generated by generate_assets.py --theme-only
// Source: core/assets-generator/meta/design-tokens.json
// 正典：docs/specs/07_design_system/TOKEN_REFERENCE.md · 页面禁止圈外 hex
import 'package:flutter/material.dart';

class AppTokens {
  AppTokens._();

  // ── 色彩 · 品牌与语义 ──
  static const Color cPrimary = Color(0xFF1B6DFF);
  static const Color cPrimaryDeep = Color(0xFF0E4FC4);
  static const Color cPrimaryWeak = Color(0xFFE8F1FF);
  static const Color cSuccess = Color(0xFF17C7A8);
  static const Color cSuccessWeak = Color(0xFFE2F8F4);
  static const Color cSuccessDeep = Color(0xFF0E9A80);
  static const Color cDanger = Color(0xFFF2555F);
  static const Color cDangerWeak = Color(0xFFFDEBEC);
  static const Color cDangerGradHi = Color(0xFFFF6B74);
  static const Color cWarning = Color(0xFFFF9F43);
  static const Color cWarningWeak = Color(0xFFFFF3E4);
  static const Color cWarningDeep = Color(0xFFC77E14);

  // ── 色彩 · 中性 ──
  static const Color cText = Color(0xFF18222E);
  static const Color cSub = Color(0xFF42536A);
  static const Color cMut = Color(0xFF60758D);
  static const Color cPh = Color(0xFF9AA8B6);
  static const Color cLine = Color(0xFFE3EAF3);
  static const Color cLineSoft = Color(0xFFEDF2F9);
  static const Color cFill = Color(0xFFF1F5FB);
  static const Color cBg = Color(0xFFF8FBFF);
  static const Color cCard = Color(0xFFFFFFFF);

  // ── 色彩 · 控制台深色 ──
  static const Color cInk = Color(0xFF101521);
  static const Color cInkLine = Color(0xFF263149);
  static const Color cInkText = Color(0xFFD6E2F5);

  // ── 色彩 · 日志六色（浅底变体） ──
  static const Color logSys = Color(0xFF5E7EA6);
  static const Color logSysBg = Color(0xFFEDF3FA);
  static const Color logErr = Color(0xFFF2555F);
  static const Color logErrBg = Color(0xFFFDEBEC);
  static const Color logRead = Color(0xFFC77E14);
  static const Color logReadBg = Color(0xFFFFF6E8);
  static const Color logWrite = Color(0xFF1B6DFF);
  static const Color logWriteBg = Color(0xFFE8F1FF);
  static const Color logRecv = Color(0xFF7C5CFF);
  static const Color logRecvBg = Color(0xFFF0EBFF);
  static const Color logOk = Color(0xFF17C7A8);
  static const Color logOkBg = Color(0xFFE2F8F4);

  // ── 色彩 · 日志六色（dock 深色变体） ──
  static const Color logDockSys = Color(0xFF9FB6D6);
  static const Color logDockSysBg = Color(0xFF1B2536);
  static const Color logDockErr = Color(0xFFFF8B94);
  static const Color logDockErrBg = Color(0xFF3A1F26);
  static const Color logDockRead = Color(0xFFFFC37E);
  static const Color logDockReadBg = Color(0xFF39301C);
  static const Color logDockWrite = Color(0xFF8FB8FF);
  static const Color logDockWriteBg = Color(0xFF1B2B4A);
  static const Color logDockRecv = Color(0xFFBBA8FF);
  static const Color logDockRecvBg = Color(0xFF2A2344);
  static const Color logDockOk = Color(0xFF5EE0C4);
  static const Color logDockOkBg = Color(0xFF14342E);

  // ── 色彩 · 组件级登记值（COMPONENT_CONTRACT） ──
  static const Color avatarGradEnd = Color(0xFFDCE9FF);
  static const Color shidAvatarStart = Color(0xFFD9F6F0);
  static const Color noteInfoFg = Color(0xFF2E5290);
  static const Color noteWarnFg = Color(0xFF8A5410);
  static const Color toastOkIcon = Color(0xFF4CDDBE);
  static const Color reviewSub = Color(0xFF7C8DA6);
  static const Color reviewLabel = Color(0xFF8FA3C0);
  static const Color otaBarGradHi = Color(0xFF5B9BFF);
  static const Color dangerOverFg = Color(0xFFFF8B94);

  // ── 字号（375 基准 px）与字重 ──
  static const double fsDisplay = 24;
  static const FontWeight fsDisplayW = fwXbold;
  static const double fsTitle = 20;
  static const FontWeight fsTitleW = fwXbold;
  static const double fsH1 = 17;
  static const FontWeight fsH1W = fwBold;
  static const double fsH2 = 15;
  static const FontWeight fsH2W = fwBold;
  static const double fsBody = 13;
  static const FontWeight fsBodyW = fwReg;
  static const double fsCap = 12;
  static const FontWeight fsCapW = fwMed;
  static const double fsMini = 11;
  static const FontWeight fsMiniW = fwMed;
  static const double fsMicro = 10;
  static const FontWeight fsMicroW = fwXbold;

  // ── 字重 ──
  static const FontWeight fwReg = FontWeight.w400;
  static const FontWeight fwMed = FontWeight.w600;
  static const FontWeight fwBold = FontWeight.w700;
  static const FontWeight fwXbold = FontWeight.w800;
  static const double lhTitle = 1.3;
  static const double lhBody = 1.55;

  // ── 字体族 ──
  static const String fontFamily = '-apple-system, BlinkMacSystemFont, "PingFang SC", "Helvetica Neue", sans-serif';
  static const String fontMono = '"SF Mono", Menlo, Consolas, monospace';

  // ── 间距（4px 基准） ──
  static const double sp1 = 4;
  static const double sp2 = 8;
  static const double sp3 = 12;
  static const double sp4 = 16;
  static const double sp5 = 20;
  static const double sp6 = 24;
  static const double sp7 = 28;
  static const double sp8 = 32;

  // ── 圆角 ──
  static const double rSm = 8;
  static const double rMd = 12;
  static const double rLg = 16;
  static const double rXl = 20;
  static const double rRound = 999;

  // ── 阴影 ──
  static const List<BoxShadow> shadow1 = [
    BoxShadow(offset: Offset(0, 1), blurRadius: 2, color: Color.fromRGBO(16, 32, 64, 0.04)),
    BoxShadow(offset: Offset(0, 4), blurRadius: 12, color: Color.fromRGBO(16, 32, 64, 0.06)),
  ];
  static const List<BoxShadow> shadow2 = [
    BoxShadow(offset: Offset(0, 8), blurRadius: 24, color: Color.fromRGBO(16, 32, 64, 0.16)),
  ];
  static const List<BoxShadow> shadowPrimary = [
    BoxShadow(offset: Offset(0, 6), blurRadius: 16, color: Color.fromRGBO(27, 109, 255, 0.32)),
  ];

  // ── 层级（Stack 顺序参考；Flutter 以树序表达） ──
  static const int zNav = 10;
  static const int zTab = 20;
  static const int zSheet = 80;
  static const int zModal = 90;
  static const int zToast = 100;

  // ── 动效 ──
  static const int durFast = 120;
  static const int dur = 200;
  static const int spinnerMs = 800;
  static const Curve ease = Curves.easeOutCubic; // cubic-bezier(.2,.7,.3,1)
}
