"""
SmartBLE — SSOT Asset Generator
================================
Reads canonical sources from core/ and deploys generated/shared files
to all target platforms. Run from any directory:

    python core/assets-generator/generate_assets.py

Outputs
-------
1. Theme CSS  → Electron, Tauri, UniApp (app_theme.css)
              → Flutter (app_colors.dart)
1b. Design Tokens (UI-PARITY-G0, 2026-09-09) → UniApp (styles/tokens.css)
                                           → Flutter (lib/ui/design/app_tokens.dart)
    Source of truth: meta/design-tokens.json (docs/specs/07_design_system/TOKEN_REFERENCE.md)
2. i18n JSON  → Electron, Tauri, UniApp
             → Flutter (.arb)
             → iOS (Localizable.strings)
3. Web Components → Electron public/components/, Tauri src/components/
4. Desktop Shared JS → Electron public/, Tauri src/

Usage:
    python core/assets-generator/generate_assets.py               # 全量
    python core/assets-generator/generate_assets.py --theme-only  # 仅 1 + 1b（Token 收口通道）
"""

import json
import os
import re
import shutil
import sys
from pathlib import Path

# ── Path Setup ────────────────────────────────────────────────────────────────
BASE_DIR     = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent.parent
META_DIR     = BASE_DIR / "meta"
GENERATED_DIR = META_DIR / "images" / "generated"
COTAURI_SRC       = PROJECT_ROOT / "apps/desktop/tauri/src"
WEB_COMPONENTS_DIR = PROJECT_ROOT / "core/ble-core/components"
SHARED_JS_DIR      = PROJECT_ROOT / "core/ble-core/desktop-shared"

# --- Static Graphics Image Target Dirs ---
IMAGE_SOURCE_DIR  = META_DIR / "images"
MASTER_ICON       = IMAGE_SOURCE_DIR / "master_icon.png"

FLUTTER_ANDROID_MIPMAP = PROJECT_ROOT / "apps/flutter/android/app/src/main/res"
TAURI_ICONS       = PROJECT_ROOT / "apps/desktop/tauri/src-tauri/icons"
UNIAPP_RES        = PROJECT_ROOT / "apps/uniapp/unpackage/res/icons"
UNIAPP_STATIC     = PROJECT_ROOT / "apps/uniapp/static"
FLUTTER_ASSETS    = PROJECT_ROOT / "apps/flutter/assets"
IOS_RESOURCES     = PROJECT_ROOT / "apps/ios/Sources/Resources"
ANDROID_RES       = PROJECT_ROOT / "apps/android/app/src/main/res"


ELECTRON_PUBLIC = PROJECT_ROOT / "apps/desktop/electron/public"
TAURI_SRC       = PROJECT_ROOT / "apps/desktop/tauri/src"

# ── Helpers ───────────────────────────────────────────────────────────────────
def load_json(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def write_file(filepath, content):
    """Write text content; create parent dirs as needed."""
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

def copy_file(src, dst):
    """Copy a single file; create parent dirs as needed."""
    dst = Path(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)

def copy_dir_contents(src_dir, dst_dir, pattern="*.js"):
    """Copy all files matching pattern from src_dir to dst_dir."""
    src_dir, dst_dir = Path(src_dir), Path(dst_dir)
    copied = []
    for f in src_dir.glob(pattern):
        copy_file(f, dst_dir / f.name)
        copied.append(f.name)
    return copied

def copy_if_exists(src, dst):
    src = Path(src)
    if src.exists():
        copy_file(src, dst)
        return True
    return False

# ── 1. Theme (CSS + Dart) ─────────────────────────────────────────────────────
def generate_theme(colors_data):
    theme = colors_data.get('theme', {})

    # CSS -------------------------------------------------------------------
    css = "/* Auto-generated by generate_assets.py — edit core/assets-generator/meta/colors.json */\n\n:root {\n"
    for key, value in theme.items():
        css += f"  --{key.replace('_', '-')}: {value['light']};\n"
    css += "}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n"
    for key, value in theme.items():
        css += f"    --{key.replace('_', '-')}: {value['dark']};\n"
    css += "  }\n}\n"

    for dst in [
        ELECTRON_PUBLIC / "app_theme.css",
        TAURI_SRC       / "app_theme.css",
        PROJECT_ROOT    / "apps/uniapp/app_theme.css",
    ]:
        write_file(dst, css)
    print(f"  ✓ app_theme.css → Electron, Tauri, UniApp")

    # Dart ------------------------------------------------------------------
    import re
    
    def snake_to_camel(name):
        parts = name.split('_')
        return parts[0] + ''.join(word.title() for word in parts[1:])

    def dart_color(hex_str, fallback_hex):
        if hex_str.startswith('rgba'):
            match = re.search(r'rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)', hex_str)
            if match:
                r, g, b, a = match.groups()
                return f"Color.fromRGBO({r}, {g}, {b}, {a})"
            return f"Color({fallback_hex})"
        return f"Color({hex_str.replace('#', '0xFF')})"

    dart = (
        "// Auto-generated by generate_assets.py\n"
        "// Source: core/assets-generator/meta/colors.json\n"
        "import 'package:flutter/material.dart';\n\n"
        "class AppColors {\n"
        "  // Light mode\n"
    )
    for key, value in theme.items():
        dart += f"  static const Color {snake_to_camel(key)}Light = {dart_color(value['light'], '0x00000000')};\n"
    dart += "\n  // Dark mode\n"
    for key, value in theme.items():
        dart += f"  static const Color {snake_to_camel(key)}Dark = {dart_color(value['dark'],  '0x00000000')};\n"
    dart += "}\n"

    write_file(PROJECT_ROOT / "apps/flutter/lib/core/theme/app_colors.dart", dart)
    print("  ✓ app_colors.dart → Flutter")

# ── 1b. Design Tokens (UI-PARITY-G0) ─────────────────────────────────────────
def generate_design_tokens(tokens):
    """distribute meta/design-tokens.json → uniapp styles/tokens.css + flutter app_tokens.dart"""
    color, font, space, radius, shadow, z, motion = (
        tokens['color'], tokens['font'], tokens['space'], tokens['radius'], tokens['shadow'], tokens['z'], tokens['motion'])

    header = "/* Auto-generated by generate_assets.py --theme-only — edit core/assets-generator/meta/design-tokens.json */\n" \
             "/* 正典：docs/specs/07_design_system/TOKEN_REFERENCE.md · 数值圈外即违例 */\n"

    # CSS ---------------------------------------------------------------
    def rgba(css_color):
        return f"rgba({','.join(str(c) for c in css_color)})"

    def _to_kebab(name):
        return re.sub(r'(?<!^)(?=[A-Z])', '-', name).lower()

    css = header + ":root {\n"
    for group, keys in (('品牌与语义', color['brand']), ('中性', color['neutral']), ('控制台深色', color['ink'])):
        css += f"  /* {group} */\n"
        for key, spec in keys.items():
            css += f"  {spec['css']}: {spec['value']};\n"
    css += "  /* 组件级登记值（COMPONENT_CONTRACT） */\n"
    for key, spec in color['derived'].items():
        if key == '_doc':
            continue
        css += f"  --c-{_to_kebab(spec['dart'])}: {spec['value']};\n"
    css += "  /* 日志六色（浅底变体） */\n"
    for key, spec in color['log'].items():
        if not key.startswith('dock'):
            css += f"  {spec['cssFg']}: {spec['fg']};  {spec['cssBg']}: {spec['bg']};\n"
    css += "  /* 字号/字重 */\n"
    for key, spec in font['size'].items():
        css += f"  {spec['css']}: {spec['value'] * 2}rpx;\n"
    for key, spec in font['weight'].items():
        css += f"  {spec['css']}: {spec['value']};\n"
    css += "  /* 字体族 */\n"
    for key, spec in font['family'].items():
        css += f"  {spec['css']}: {spec['value']};\n"
    css += "  /* 间距 4 基准（px×2→rpx） */\n"
    for key in [k for k in space if k.startswith('sp')]:
        css += f"  {space[key]['css']}: {space[key]['value'] * 2}rpx;\n"
    css += "  /* 圆角（px×2→rpx） */\n"
    for key, spec in radius.items():
        css += f"  {spec['css']}: {spec['value'] * 2}rpx;\n"
    css += "  /* 阴影/层级/动效 */\n"
    for key, spec in shadow.items():
        layers = ', '.join(f"{l['x']}px {l['y']}px {l['blur']}px {rgba(l['color'])}" for l in spec['layers'])
        css += f"  {spec['css']}: {layers};\n"
    for key, spec in z.items():
        css += f"  {spec['css']}: {spec['value']};\n"
    for key in ('durFast', 'dur'):
        css += f"  {motion[key]['css']}: {motion[key]['value']}ms;\n"
    css += f"  --ease: {motion['ease']['value']};\n"
    css += "}\n"
    write_file(PROJECT_ROOT / "apps/uniapp/styles/tokens.css", css)
    print("  ✓ styles/tokens.css → UniApp")

    # Dart ---------------------------------------------------------------
    def dart_color(hex_str):
        return f"Color({hex_str.replace('#', '0xFF')})"

    dart = "// Auto-generated by generate_assets.py --theme-only\n" \
           "// Source: core/assets-generator/meta/design-tokens.json\n" \
           "// 正典：docs/specs/07_design_system/TOKEN_REFERENCE.md · 页面禁止圈外 hex\n" \
           "import 'package:flutter/material.dart';\n\n" \
           "class AppTokens {\n" \
           "  AppTokens._();\n\n" \
           "  // ── 色彩 · 品牌与语义 ──\n"
    for key, spec in color['brand'].items():
        dart += f"  static const Color {spec['dart']} = {dart_color(spec['value'])};\n"
    dart += "\n  // ── 色彩 · 中性 ──\n"
    for key, spec in color['neutral'].items():
        dart += f"  static const Color {spec['dart']} = {dart_color(spec['value'])};\n"
    dart += "\n  // ── 色彩 · 控制台深色 ──\n"
    for key, spec in color['ink'].items():
        dart += f"  static const Color {spec['dart']} = {dart_color(spec['value'])};\n"
    dart += "\n  // ── 色彩 · 日志六色（浅底变体） ──\n"
    for key, spec in color['log'].items():
        if not key.startswith('dock'):
            dart += f"  static const Color {spec['dart']} = {dart_color(spec['fg'])};\n"
            dart += f"  static const Color {spec['dart']}Bg = {dart_color(spec['bg'])};\n"
    dart += "\n  // ── 色彩 · 日志六色（dock 深色变体） ──\n"
    for key, spec in color['log'].items():
        if key.startswith('dock'):
            dart += f"  static const Color {spec['dart']} = {dart_color(spec['fg'])};\n"
            dart += f"  static const Color {spec['dart']}Bg = {dart_color(spec['bg'])};\n"
    dart += "\n  // ── 色彩 · 组件级登记值（COMPONENT_CONTRACT） ──\n"
    for key, spec in color['derived'].items():
        if key == '_doc':
            continue
        dart += f"  static const Color {spec['dart']} = {dart_color(spec['value'])};\n"

    dart += "\n  // ── 字号（375 基准 px）与字重 ──\n"
    for key, spec in font['size'].items():
        wkey = {400: 'reg', 600: 'med', 700: 'bold', 800: 'xbold'}[spec['weight']]
        dart += f"  static const double {spec['dart']} = {spec['value']};\n"
        dart += f"  static const FontWeight {spec['dart']}W = {font['weight'][wkey]['dart']};\n"
    dart += "\n  // ── 字重 ──\n"
    for key, spec in font['weight'].items():
        dart += f"  static const FontWeight {spec['dart']} = FontWeight.w{spec['value']};\n"
    dart += f"  static const double lhTitle = {font['lineHeight']['title']};\n"
    dart += f"  static const double lhBody = {font['lineHeight']['body']};\n"
    dart += "\n  // ── 字体族 ──\n"
    dart += f"  static const String fontFamily = '{font['family']['sans']['value']}';\n"
    dart += f"  static const String fontMono = '{font['family']['mono']['value']}';\n"

    dart += "\n  // ── 间距（4px 基准） ──\n"
    for key in [k for k in space if k.startswith('sp')]:
        dart += f"  static const double {space[key]['dart']} = {space[key]['value']};\n"
    dart += "\n  // ── 圆角 ──\n"
    for key, spec in radius.items():
        dart += f"  static const double {spec['dart']} = {spec['value']};\n"

    dart += "\n  // ── 阴影 ──\n"
    for key, spec in shadow.items():
        layers = ',\n    '.join(
            f"BoxShadow(offset: Offset({l['x']}, {l['y']}), blurRadius: {l['blur']}, color: Color.fromRGBO({', '.join(str(c) for c in l['color'])}))"
            for l in spec['layers'])
        dart += f"  static const List<BoxShadow> {spec['dart']} = [\n    {layers},\n  ];\n"

    dart += "\n  // ── 层级（Stack 顺序参考；Flutter 以树序表达） ──\n"
    for key, spec in z.items():
        dart += f"  static const int {spec['dart']} = {spec['value']};\n"

    dart += "\n  // ── 动效 ──\n"
    dart += f"  static const int {motion['durFast']['dart']} = {motion['durFast']['value']};\n"
    dart += f"  static const int {motion['dur']['dart']} = {motion['dur']['value']};\n"
    dart += f"  static const int {motion['spinner']['dart']} = {motion['spinner']['value']};\n"
    dart += f"  static const Curve ease = {motion['ease']['dartValue']}; // {motion['ease']['value']}\n"
    dart += "}\n"

    write_file(PROJECT_ROOT / "apps/flutter/lib/ui/design/app_tokens.dart", dart)
    print("  ✓ lib/ui/design/app_tokens.dart → Flutter")

# ── 2. i18n ───────────────────────────────────────────────────────────────────
def generate_i18n():
    locales = ['zh-CN', 'en-US']
    for loc in locales:
        data      = load_json(META_DIR / f"i18n_{loc}.json")
        loc_short = loc.split('-')[0]

        # Web JSON (Electron + Tauri + UniApp) --------------------------------
        json_str = json.dumps(data, ensure_ascii=False, indent=2)
        for dst in [
            ELECTRON_PUBLIC / f"locales/{loc}.json",
            TAURI_SRC       / f"locales/{loc}.json",
            PROJECT_ROOT    / f"apps/uniapp/locale/{loc}.json",
        ]:
            write_file(dst, json_str)
        print(f"  ✓ {loc}.json → Electron, Tauri, UniApp")

        # Flutter ARB ---------------------------------------------------------
        arb = {"@@locale": loc_short}
        for k, v in data.items():
            arb[k] = v
            params = re.findall(r'\{([a-zA-Z0-9_]+)\}', v)
            if params:
                arb[f"@{k}"] = {"placeholders": {p: {"type": "String"} for p in params}}
        write_file(PROJECT_ROOT / f"apps/flutter/lib/l10n/app_{loc_short}.arb",
                   json.dumps(arb, ensure_ascii=False, indent=2))
        print(f"  ✓ app_{loc_short}.arb → Flutter")

        # iOS Localizable.strings --------------------------------------------
        ios_dir = "zh-Hans" if loc == "zh-CN" else "en"
        ios = f"/* Auto-generated from {loc} */\n"
        for k, v in data.items():
            ios += f'"{k}" = "{re.sub(r"{[a-zA-Z0-9_]+}", "%@", v)}";\n'
        write_file(PROJECT_ROOT / f"apps/ios/Sources/Resources/{ios_dir}.lproj/Localizable.strings", ios)
        print(f"  ✓ {ios_dir}/Localizable.strings → iOS")

# ── 3. Web Components ─────────────────────────────────────────────────────────
def sync_web_components():
    """
    Deploy shared Web Components from core/ble-core/components/ to both
    Electron and Tauri component directories.

    Canonical source: core/ble-core/components/*.js
    Targets:
      apps/desktop/electron/public/components/
      apps/desktop/tauri/src/components/
    """
    if not WEB_COMPONENTS_DIR.exists():
        print(f"  ⚠ components dir not found: {WEB_COMPONENTS_DIR}")
        return

    for dst_dir in [
        ELECTRON_PUBLIC / "components",
        TAURI_SRC       / "components",
    ]:
        copied = copy_dir_contents(WEB_COMPONENTS_DIR, dst_dir, "*.js")
        if copied:
            print(f"  ✓ Web Components ({', '.join(copied)}) → {dst_dir.relative_to(PROJECT_ROOT)}")

# ── 4. Desktop Shared JS ─────────────────────────────────────────────────────
def sync_shared_js():
    """
    Deploy shared JS utilities from core/ble-core/desktop-shared/ to both
    Electron and Tauri source directories.

    Canonical source: core/ble-core/desktop-shared/*.js
    Targets:
      apps/desktop/electron/public/
      apps/desktop/tauri/src/
    """
    if not SHARED_JS_DIR.exists():
        print(f"  ⚠ desktop-shared dir not found: {SHARED_JS_DIR}")
        return

    for dst_dir in [ELECTRON_PUBLIC, TAURI_SRC]:
        copied = copy_dir_contents(SHARED_JS_DIR, dst_dir, "*.js")
        if copied:
            print(f"  ✓ Shared JS ({', '.join(copied)}) → {dst_dir.relative_to(PROJECT_ROOT)}")

# ── 5. Static Graphics (Pillow) ───────────────────────────────────────────────
def generate_graphics():
    if not MASTER_ICON.exists():
        print(f"  [SKIPPED] Master icon not found at {MASTER_ICON}")
        return

    try:
        from PIL import Image
    except ImportError:
        print("  [SKIPPED] Python Pillow library not installed. Install with: pip install Pillow")
        return

    try:
        with Image.open(MASTER_ICON) as img:
            # 1. Tauri Icons (32x32.png, 128x128.png, icon.png=512)
            for size, name in [(32, "32x32.png"), (128, "128x128.png"), (256, "128x128@2x.png"), (512, "icon.png"), (256, "Square284x284Logo.png"), (512, "Square150x150Logo.png")]:
                out = TAURI_ICONS / name
                if out.parent.exists():
                    img.resize((size, size), Image.Resampling.LANCZOS).save(out)
            # Tauri ICO (use 256)
            if TAURI_ICONS.exists():
                img.resize((256, 256), Image.Resampling.LANCZOS).save(TAURI_ICONS / "icon.ico", format="ICO")
            print("  ✓ Resized Icons → Tauri (src-tauri/icons/)")

            # 2. UniApp static logo always updates; packaged icons update when res dir exists
            img.resize((512, 512), Image.Resampling.LANCZOS).save(UNIAPP_STATIC / "logo.png")
            if UNIAPP_RES.exists():
                for size in [1024, 192, 180, 167, 152, 144, 120, 96, 87, 80, 76, 72, 60, 58, 40, 29, 20]:
                    out = UNIAPP_RES / f"{size}x{size}.png"
                    img.resize((size, size), Image.Resampling.LANCZOS).save(out)
                print("  ✓ Resized Icons → UniApp (unpackage/res & static/)")
            else:
                print("  ✓ Resized Logo → UniApp static/logo.png")

            # 3. Flutter Android Mipmap
            mipmap_scales = {
                "mipmap-mdpi": 48,
                "mipmap-hdpi": 72,
                "mipmap-xhdpi": 96,
                "mipmap-xxhdpi": 144,
                "mipmap-xxxhdpi": 192
            }
            if FLUTTER_ANDROID_MIPMAP.exists():
                for folder, size in mipmap_scales.items():
                    out_dir = FLUTTER_ANDROID_MIPMAP / folder
                    out_dir.mkdir(parents=True, exist_ok=True)
                    img.resize((size, size), Image.Resampling.LANCZOS).save(out_dir / "ic_launcher.png")
                print("  ✓ Resized Icons → Flutter Android (mipmap resources)")

            # 4. Shared Brand Assets
            brand_targets = [
                ELECTRON_PUBLIC / "brand",
                TAURI_SRC / "brand",
                FLUTTER_ASSETS / "brand",
                IOS_RESOURCES / "Brand",
            ]
            for brand_target in brand_targets:
                brand_target.mkdir(parents=True, exist_ok=True)

            shared_brand_files = [
                (PROJECT_ROOT / "apps/uniapp/static/logo.png", "icon.png"),
                (GENERATED_DIR / "smartble-about-hero.png", "about-hero.png"),
                (GENERATED_DIR / "smartble-share.png", "share.png"),
            ]
            copied_brand = []
            for src, name in shared_brand_files:
                if not src.exists():
                    continue
                for brand_target in brand_targets:
                    copy_file(src, brand_target / name)
                copied_brand.append(name)
            if copied_brand:
                print(f"  ✓ Synced Brand Assets ({', '.join(copied_brand)}) → Electron, Tauri, Flutter, iOS")

            # iOS / SwiftPM-friendly aliases
            ios_brand_dir = IOS_RESOURCES / "Brand"
            ios_aliases = [
                (PROJECT_ROOT / "apps/uniapp/static/logo.png", "brand_icon.png"),
                (GENERATED_DIR / "smartble-about-hero.png", "about_hero.png"),
                (GENERATED_DIR / "smartble-share.png", "share_card.png"),
            ]
            copied_ios_aliases = []
            for src, name in ios_aliases:
                if copy_if_exists(src, ios_brand_dir / name):
                    copied_ios_aliases.append(name)
            if copied_ios_aliases:
                print(f"  ✓ Synced Brand Aliases ({', '.join(copied_ios_aliases)}) → iOS Resources/Brand")

            # Flutter runtime app icon source
            if FLUTTER_ASSETS.exists():
                copy_file(PROJECT_ROOT / "apps/uniapp/static/logo.png", FLUTTER_ASSETS / "images/icon.png")
                print("  ✓ Synced Logo → Flutter assets/images/icon.png")

            # Android local drawable resources for Compose surfaces
            android_drawable = ANDROID_RES / "drawable"
            android_drawable.mkdir(parents=True, exist_ok=True)
            android_brand_files = [
                (PROJECT_ROOT / "apps/uniapp/static/logo.png", "brand_icon.png"),
                (GENERATED_DIR / "smartble-about-hero.png", "brand_about_hero.png"),
                (GENERATED_DIR / "smartble-share.png", "brand_share.png"),
            ]
            copied_android = []
            for src, name in android_brand_files:
                if copy_if_exists(src, android_drawable / name):
                    copied_android.append(name)
            if copied_android:
                print(f"  ✓ Synced Brand Assets ({', '.join(copied_android)}) → Android drawable")
                
            # 5. Copy Placeholder Assets
            import shutil
            placeholders_src = IMAGE_SOURCE_DIR / "placeholders"
            if placeholders_src.exists():
                placeholder_files = list(placeholders_src.glob("*.svg")) + list(placeholders_src.glob("*.png"))
                for ph_target in [
                    ELECTRON_PUBLIC / "placeholders",
                    TAURI_SRC / "placeholders",
                    UNIAPP_STATIC / "placeholders"
                ]:
                    ph_target.mkdir(parents=True, exist_ok=True)
                    for placeholder_file in placeholder_files:
                        shutil.copy2(placeholder_file, ph_target / placeholder_file.name)
                print("  ✓ Copied Placeholder Assets (.svg/.png) → Tauri, Electron, UniApp")
                
    except Exception as e:
        print(f"  [ERROR] generating graphics: {e}")


# -- Entry Point ---------------------------------------------------------------
if __name__ == "__main__":
    import sys
    # Ensure UTF-8 output on Windows (Python 3.7+)
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')

    theme_only = "--theme-only" in sys.argv

    print("\nSmartBLE Asset Generator")
    print("-" * 40)

    colors_data = load_json(META_DIR / "colors.json")
    tokens_data = load_json(META_DIR / "design-tokens.json")

    print("\n[1/5] Theme (CSS + Dart)...")
    generate_theme(colors_data)

    print("\n[2/5] Design Tokens (UI-PARITY-G0)...")
    generate_design_tokens(tokens_data)

    if theme_only:
        print("\n--theme-only: skip i18n / components / shared-js / graphics.\nAll theme assets generated successfully.\n")
        sys.exit(0)

    print("\n[3/5] i18n...")
    generate_i18n()

    print("\n[4/5] Web Components + Desktop Shared JS...")
    sync_web_components()
    sync_shared_js()

    print("\n[5/5] Static Graphics...")
    generate_graphics()

    print("\nAll assets generated successfully.\n")
