"""
SmartBLE — SSOT Asset Generator
================================
Reads canonical sources from core/ and deploys generated/shared files
to all target platforms. Run from any directory:

    python core/assets-generator/generate_assets.py

Outputs
-------
1. Theme CSS  → Electron, Tauri, UniApp (app_theme.css)
              → Flutter (app_colors.dart)
2. i18n JSON  → Electron, Tauri, UniApp
             → Flutter (.arb)
             → iOS (Localizable.strings)
3. Web Components → Electron public/components/, Tauri src/components/
4. Desktop Shared JS → Electron public/, Tauri src/
"""

import json
import os
import re
import shutil
from pathlib import Path

# ── Path Setup ────────────────────────────────────────────────────────────────
BASE_DIR     = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent.parent
META_DIR     = BASE_DIR / "meta"
COTAURI_SRC       = PROJECT_ROOT / "apps/desktop/tauri/src"
WEB_COMPONENTS_DIR = PROJECT_ROOT / "core/ble-core/components"
SHARED_JS_DIR      = PROJECT_ROOT / "core/ble-core/desktop-shared"

# --- Static Graphics Image Target Dirs ---
IMAGE_SOURCE_DIR  = META_DIR / "images"
MASTER_ICON       = IMAGE_SOURCE_DIR / "master_icon.png"

FLUTTER_ANDROID_MIPMAP = PROJECT_ROOT / "apps/flutter/android/app/src/main/res"
TAURI_ICONS       = PROJECT_ROOT / "apps/desktop/tauri/src-tauri/icons"
UNIAPP_RES        = PROJECT_ROOT / "apps/uniapp/unpackage/res/icons"
UNIAPP_STATIC     = PROJECT_ROOT / "apps/uniapp/static"


ELECTRON_PUBLIC = PROJECT_ROOT / "apps/desktop/electron/public"
TAURI_SRC       = PROJECT_ROOT / "apps/desktop/tauri/src"

# ── Helpers ───────────────────────────────────────────────────────────────────
def load_json(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def write_file(filepath, content):
    """Write text content; create parent dirs as needed."""
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

def copy_file(src, dst):
    """Copy a single file; create parent dirs as needed."""
    dst = Path(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)

def copy_dir_contents(src_dir, dst_dir, pattern="*.js"):
    """Copy all files matching pattern from src_dir to dst_dir."""
    src_dir, dst_dir = Path(src_dir), Path(dst_dir)
    copied = []
    for f in src_dir.glob(pattern):
        copy_file(f, dst_dir / f.name)
        copied.append(f.name)
    return copied

# ── 1. Theme (CSS + Dart) ─────────────────────────────────────────────────────
def generate_theme(colors_data):
    theme = colors_data.get('theme', {})

    # CSS -------------------------------------------------------------------
    css = "/* Auto-generated by generate_assets.py — edit core/assets-generator/meta/colors.json */\n\n:root {\n"
    for key, value in theme.items():
        css += f"  --{key.replace('_', '-')}: {value['light']};\n"
    css += "}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n"
    for key, value in theme.items():
        css += f"    --{key.replace('_', '-')}: {value['dark']};\n"
    css += "  }\n}\n"

    for dst in [
        ELECTRON_PUBLIC / "app_theme.css",
        TAURI_SRC       / "app_theme.css",
        PROJECT_ROOT    / "apps/uniapp/app_theme.css",
    ]:
        write_file(dst, css)
    print(f"  ✓ app_theme.css → Electron, Tauri, UniApp")

    # Dart ------------------------------------------------------------------
    import re
    
    def snake_to_camel(name):
        parts = name.split('_')
        return parts[0] + ''.join(word.title() for word in parts[1:])

    def dart_color(hex_str, fallback_hex):
        if hex_str.startswith('rgba'):
            match = re.search(r'rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)', hex_str)
            if match:
                r, g, b, a = match.groups()
                return f"Color.fromRGBO({r}, {g}, {b}, {a})"
            return f"Color({fallback_hex})"
        return f"Color({hex_str.replace('#', '0xFF')})"

    dart = (
        "// Auto-generated by generate_assets.py\n"
        "// Source: core/assets-generator/meta/colors.json\n"
        "import 'package:flutter/material.dart';\n\n"
        "class AppColors {\n"
        "  // Light mode\n"
    )
    for key, value in theme.items():
        dart += f"  static const Color {snake_to_camel(key)}Light = {dart_color(value['light'], '0x00000000')};\n"
    dart += "\n  // Dark mode\n"
    for key, value in theme.items():
        dart += f"  static const Color {snake_to_camel(key)}Dark = {dart_color(value['dark'],  '0x00000000')};\n"
    dart += "}\n"

    write_file(PROJECT_ROOT / "apps/flutter/lib/core/theme/app_colors.dart", dart)
    print("  ✓ app_colors.dart → Flutter")

# ── 2. i18n ───────────────────────────────────────────────────────────────────
def generate_i18n():
    locales = ['zh-CN', 'en-US']
    for loc in locales:
        data      = load_json(META_DIR / f"i18n_{loc}.json")
        loc_short = loc.split('-')[0]

        # Web JSON (Electron + Tauri + UniApp) --------------------------------
        json_str = json.dumps(data, ensure_ascii=False, indent=2)
        for dst in [
            ELECTRON_PUBLIC / f"locales/{loc}.json",
            TAURI_SRC       / f"locales/{loc}.json",
            PROJECT_ROOT    / f"apps/uniapp/locale/{loc}.json",
        ]:
            write_file(dst, json_str)
        print(f"  ✓ {loc}.json → Electron, Tauri, UniApp")

        # Flutter ARB ---------------------------------------------------------
        arb = {"@@locale": loc_short}
        for k, v in data.items():
            arb[k] = v
            params = re.findall(r'\{([a-zA-Z0-9_]+)\}', v)
            if params:
                arb[f"@{k}"] = {"placeholders": {p: {"type": "String"} for p in params}}
        write_file(PROJECT_ROOT / f"apps/flutter/lib/l10n/app_{loc_short}.arb",
                   json.dumps(arb, ensure_ascii=False, indent=2))
        print(f"  ✓ app_{loc_short}.arb → Flutter")

        # iOS Localizable.strings --------------------------------------------
        ios_dir = "zh-Hans" if loc == "zh-CN" else "en"
        ios = f"/* Auto-generated from {loc} */\n"
        for k, v in data.items():
            ios += f'"{k}" = "{re.sub(r"{[a-zA-Z0-9_]+}", "%@", v)}";\n'
        write_file(PROJECT_ROOT / f"apps/ios/Sources/Resources/{ios_dir}.lproj/Localizable.strings", ios)
        print(f"  ✓ {ios_dir}/Localizable.strings → iOS")

# ── 3. Web Components ─────────────────────────────────────────────────────────
def sync_web_components():
    """
    Deploy shared Web Components from core/ble-core/components/ to both
    Electron and Tauri component directories.

    Canonical source: core/ble-core/components/*.js
    Targets:
      apps/desktop/electron/public/components/
      apps/desktop/tauri/src/components/
    """
    if not WEB_COMPONENTS_DIR.exists():
        print(f"  ⚠ components dir not found: {WEB_COMPONENTS_DIR}")
        return

    for dst_dir in [
        ELECTRON_PUBLIC / "components",
        TAURI_SRC       / "components",
    ]:
        copied = copy_dir_contents(WEB_COMPONENTS_DIR, dst_dir, "*.js")
        if copied:
            print(f"  ✓ Web Components ({', '.join(copied)}) → {dst_dir.relative_to(PROJECT_ROOT)}")

# ── 4. Desktop Shared JS ─────────────────────────────────────────────────────
def sync_shared_js():
    """
    Deploy shared JS utilities from core/ble-core/desktop-shared/ to both
    Electron and Tauri source directories.

    Canonical source: core/ble-core/desktop-shared/*.js
    Targets:
      apps/desktop/electron/public/
      apps/desktop/tauri/src/
    """
    if not SHARED_JS_DIR.exists():
        print(f"  ⚠ desktop-shared dir not found: {SHARED_JS_DIR}")
        return

    for dst_dir in [ELECTRON_PUBLIC, TAURI_SRC]:
        copied = copy_dir_contents(SHARED_JS_DIR, dst_dir, "*.js")
        if copied:
            print(f"  ✓ Shared JS ({', '.join(copied)}) → {dst_dir.relative_to(PROJECT_ROOT)}")

# ── 5. Static Graphics (Pillow) ───────────────────────────────────────────────
def generate_graphics():
    if not MASTER_ICON.exists():
        print(f"  [SKIPPED] Master icon not found at {MASTER_ICON}")
        return

    try:
        from PIL import Image
    except ImportError:
        print("  [SKIPPED] Python Pillow library not installed. Install with: pip install Pillow")
        return

    try:
        with Image.open(MASTER_ICON) as img:
            # 1. Tauri Icons (32x32.png, 128x128.png, icon.png=512)
            for size, name in [(32, "32x32.png"), (128, "128x128.png"), (256, "128x128@2x.png"), (512, "icon.png"), (256, "Square284x284Logo.png"), (512, "Square150x150Logo.png")]:
                out = TAURI_ICONS / name
                if out.parent.exists():
                    img.resize((size, size), Image.Resampling.LANCZOS).save(out)
            # Tauri ICO (use 256)
            if TAURI_ICONS.exists():
                img.resize((256, 256), Image.Resampling.LANCZOS).save(TAURI_ICONS / "icon.ico", format="ICO")
            print("  ✓ Resized Icons → Tauri (src-tauri/icons/)")

            # 2. UniApp Icons (1024, 192, 144, 96, 72, 48 + static/logo.png)
            if UNIAPP_RES.exists():
                for size in [1024, 192, 180, 167, 152, 144, 120, 96, 87, 80, 76, 72, 60, 58, 40, 29, 20]:
                    out = UNIAPP_RES / f"{size}x{size}.png"
                    img.resize((size, size), Image.Resampling.LANCZOS).save(out)
                img.resize((512, 512), Image.Resampling.LANCZOS).save(UNIAPP_STATIC / "logo.png")
                print("  ✓ Resized Icons → UniApp (unpackage/res & static/)")

            # 3. Flutter Android Mipmap
            mipmap_scales = {
                "mipmap-mdpi": 48,
                "mipmap-hdpi": 72,
                "mipmap-xhdpi": 96,
                "mipmap-xxhdpi": 144,
                "mipmap-xxxhdpi": 192
            }
            if FLUTTER_ANDROID_MIPMAP.exists():
                for folder, size in mipmap_scales.items():
                    out_dir = FLUTTER_ANDROID_MIPMAP / folder
                    out_dir.mkdir(parents=True, exist_ok=True)
                    img.resize((size, size), Image.Resampling.LANCZOS).save(out_dir / "ic_launcher.png")
                print("  ✓ Resized Icons → Flutter Android (mipmap resources)")
                
            # 4. Copy Vector Placeholders
            import shutil
            placeholders_src = IMAGE_SOURCE_DIR / "placeholders"
            if placeholders_src.exists():
                for ph_target in [
                    ELECTRON_PUBLIC / "placeholders",
                    TAURI_SRC / "placeholders",
                    UNIAPP_STATIC / "placeholders"
                ]:
                    ph_target.mkdir(parents=True, exist_ok=True)
                    for svg_file in placeholders_src.glob("*.svg"):
                        shutil.copy2(svg_file, ph_target / svg_file.name)
                print("  ✓ Copied SVG Placeholders → Tauri, Electron, UniApp")
                
    except Exception as e:
        print(f"  [ERROR] generating graphics: {e}")


# -- Entry Point ---------------------------------------------------------------
if __name__ == "__main__":
    import sys
    # Ensure UTF-8 output on Windows (Python 3.7+)
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')

    print("\nSmartBLE Asset Generator")
    print("-" * 40)

    colors_data = load_json(META_DIR / "colors.json")

    print("\n[1/4] Theme (CSS + Dart)...")
    generate_theme(colors_data)

    print("\n[2/4] i18n...")
    generate_i18n()

    print("\n[3/4] Web Components...")
    sync_web_components()

    print("\n[4/5] Desktop Shared JS...")
    sync_shared_js()

    print("\n[5/5] Static Graphics...")
    generate_graphics()

    print("\nAll assets generated successfully.\n")
