// Generated by scripts/generate-release-metadata.mjs — DO NOT EDIT.
// F027 版本元数据：apps/uniapp/config/release-metadata.generated.js 的 Kotlin 锁定镜像，
// 与 uniapp 产物出自同一确定性管线；版本唯一事实源 = 仓库根 VERSION。
package com.smartble.core.config

val RELEASE_METADATA: Map<String, Any?> = mapOf(
  "schema_version" to "1.0",
  "channel" to "preview",
  "release_tag" to null,
  "app_version" to "1.0.5",
  "app_build_code" to 101,
  "commit" to null,
  "built_at" to null,
  "overall_status" to "PREVIEW",
  "artifacts" to emptyList<Any?>(),
  "public_surfaces" to mapOf(
    "android" to mapOf(
      "name" to "UniApp Android",
      "role" to "mainline",
      "capability_status" to "PREVIEW",
      "release_status" to "NOT_RELEASED",
      "artifact" to null,
    ),
    "h5" to mapOf(
      "name" to "H5",
      "role" to "degradation",
      "capability_status" to "UNSUPPORTED",
      "release_status" to "NOT_RELEASED",
    ),
    "ios" to mapOf(
      "name" to "iOS",
      "role" to "mainline",
      "capability_status" to "PREVIEW",
      "release_status" to "NOT_RELEASED",
      "reason" to "纯原生 SwiftUI 功能与默认/关键交互态已实现；真机签名 E5 尚未完成",
    ),
    "flutter_tauri_native" to mapOf(
      "name" to "Flutter / Tauri / 原生端",
      "role" to "REFERENCE",
      "capability_status" to null,
      "release_status" to "NOT_RELEASED",
    ),
    "peripheral" to mapOf(
      "name" to "LightBLE ESP32 Peripheral",
      "role" to "fixture",
      "capability_status" to "PREVIEW",
      "release_status" to "NOT_RELEASED",
      "artifact" to null,
    ),
    "observer" to mapOf(
      "name" to "ESP32 Observer",
      "role" to "fixture",
      "capability_status" to "NOT_RELEASED",
      "release_status" to "NOT_RELEASED",
      "artifact" to null,
    ),
    "ota" to mapOf(
      "name" to "OTA",
      "role" to "capability",
      "capability_status" to "BLOCKED",
      "release_status" to "NOT_RELEASED",
      "reason" to "客户端与固件完整事务尚未对齐并完成 E5",
    ),
    "smart_hid" to mapOf(
      "name" to "Smart HID",
      "role" to "capability",
      "capability_status" to "PREVIEW",
      "release_status" to "NOT_RELEASED",
      "reason" to "第一方 Profile 已有实现路径，端到端 E5 未完成",
    ),
  ),
  "verified_capabilities" to emptyList<Any?>(),
  "known_limitations" to listOf(
    "Android 正式 APK 尚未发布",
    "Playwright / Page Driver E4 页面驱动层为 Fake Runtime 模式（真机/真实 H5 驱动未接入）",
    "Android、ESP32 E5 真机验证尚未执行（iOS 已有真机安装+启动证据，完整 BLE E5 链未复验）",
    "OTA 当前 BLOCKED（客户端 CTRL 事务与固件契约分歧待裁决）",
    "ESP32 Observer 固件尚未完成",
    "Smart HID 尚未完成端到端 E5",
    "Release Pipeline 已切换为 CI 候选产物模式（preview 渠道，artifacts 空，不自动发布）；UniApp Android 正式 APK 仍由 HBuilderX 打包，尚未管线化",
    "微信小程序运行目标已于 2026-09-11 退役（历史文档与冻结原型保留）",
  ),
  "tested_devices" to emptyList<Any?>(),
  "evidence_ids" to emptyList<Any?>(),
)
