// Generated by scripts/generate-release-metadata.mjs — DO NOT EDIT.
// F027 版本元数据：apps/uniapp/config/release-metadata.generated.js 的 Kotlin 锁定镜像，
// 与 uniapp 产物出自同一确定性管线；版本唯一事实源 = 仓库根 VERSION。
package com.smartble.core.config

val RELEASE_METADATA: Map<String, Any?> = mapOf(
  "schema_version" to "1.0",
  "channel" to "preview",
  "release_tag" to null,
  "app_version" to "1.0.5",
  "app_build_code" to 101,
  "commit" to null,
  "built_at" to null,
  "overall_status" to "PREVIEW",
  "artifacts" to emptyList<Any?>(),
  "wechat_qr" to mapOf(
    "status" to "not_released",
    "image" to null,
  ),
  "public_surfaces" to mapOf(
    "android" to mapOf(
      "name" to "UniApp Android",
      "role" to "mainline",
      "capability_status" to "PREVIEW",
      "release_status" to "NOT_RELEASED",
      "artifact" to null,
    ),
    "wechat" to mapOf(
      "name" to "BLE Toolkit+ 微信小程序",
      "role" to "mainline",
      "capability_status" to "PREVIEW",
      "release_status" to "NOT_RELEASED",
      "qr" to null,
    ),
    "h5" to mapOf(
      "name" to "H5",
      "role" to "degradation",
      "capability_status" to "UNSUPPORTED",
      "release_status" to "NOT_RELEASED",
    ),
    "ios" to mapOf(
      "name" to "iOS",
      "role" to "future",
      "capability_status" to "NOT_RELEASED",
      "release_status" to "NOT_RELEASED",
    ),
    "flutter_tauri_native" to mapOf(
      "name" to "Flutter / Tauri / 原生端",
      "role" to "REFERENCE",
      "capability_status" to null,
      "release_status" to "NOT_RELEASED",
    ),
    "peripheral" to mapOf(
      "name" to "LightBLE ESP32 Peripheral",
      "role" to "fixture",
      "capability_status" to "PREVIEW",
      "release_status" to "NOT_RELEASED",
      "artifact" to null,
    ),
    "observer" to mapOf(
      "name" to "ESP32 Observer",
      "role" to "fixture",
      "capability_status" to "NOT_RELEASED",
      "release_status" to "NOT_RELEASED",
      "artifact" to null,
    ),
    "ota" to mapOf(
      "name" to "OTA",
      "role" to "capability",
      "capability_status" to "BLOCKED",
      "release_status" to "NOT_RELEASED",
      "reason" to "客户端与固件完整事务尚未对齐并完成 E5",
    ),
    "smart_hid" to mapOf(
      "name" to "Smart HID",
      "role" to "capability",
      "capability_status" to "PREVIEW",
      "release_status" to "NOT_RELEASED",
      "reason" to "第一方 Profile 已有实现路径，端到端 E5 未完成",
    ),
  ),
  "verified_capabilities" to emptyList<Any?>(),
  "known_limitations" to listOf(
    "Android 正式 APK 尚未发布",
    "微信正式小程序码尚未发布",
    "Playwright / Page Driver E4 尚未完成",
    "Android、微信、ESP32 E5 尚未执行",
    "OTA 当前 BLOCKED",
    "ESP32 Observer 尚未完成",
    "Smart HID 尚未完成端到端 E5",
    "Release Pipeline 仍为历史 Flutter/Tauri 路线",
  ),
  "tested_devices" to emptyList<Any?>(),
  "evidence_ids" to emptyList<Any?>(),
)
